
CREATE TABLE STG_STTM_DATES (BRANCH_CODE VARCHAR(3) NOT NULL , TODAY DATE, PREV_WORKING_DAY DATE, NEXT_WORKING_DAY DATE, RECORD_STAT VARCHAR(1), AUTH_STAT VARCHAR(1), MOD_NO DECIMAL, MAKER_ID VARCHAR(12), MAKER_DT_STAMP DATE, CHECKER_ID VARCHAR(12), CHECKER_DT_STAMP DATE, ONCE_AUTH VARCHAR(1), ENTITY_CODE VARCHAR(35),  CONSTRAINT PK01_STG_STTM_DATES PRIMARY KEY (ENTITY_CODE, BRANCH_CODE)   )
